name: Bug Report
description: Einen Verbesserungsvorschlag oder Fehler melden.
title: "[3.10/4.x]: "
labels: ["bug"]
assignees:
  - tecpromotion
  - zero-24
  - heelc29
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: Was soll verbessert / korrigiert werden?
      description: Gerne mit Screenshots und Fehlermeldungen
    validations:
      required: true
 - type: textarea
    id: where-happened
    attributes:
      label: Wo wird der Sprachstring angezeigt (Frontend/Backend)
      description: Wo wird der Sprachstring angezeigt (Frontend/Backend)?
    validations:
      required: true
 - type: textarea
    id: new-translation
    attributes:
      label: Was wäre eine bessere Übersetzung / Bezeichnung
      description: Was wäre eine bessere Übersetzung / Bezeichnung?
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Joomla Version
      description: Welche Joomla Version wird verwendet?
      options:
        - 4.1.x (Empfohlen)
        - 3.10.x (Achtung, Support endet August 2023)
    validations:
      required: true
  - type: textarea
    id: moreinformations
    attributes:
      label: Zusätzlichen Informationen
      description: Platz für zusätzliche Informationen
    validations:
      required: false
