name: Bug Report
description: Use this template for issues.
title: "[3.10/4.x]: "
labels: ["enhancement"]
assignees:
  - tecpromotion
  - zero-24
  - heelc29
body:
- type: markdown
    attributes:
      value: |
        Vielen Dank, dass Du dir die Zeit genommen hast, diesen Fehlerbericht auszufüllen!
